export const REDUX_LOADING_MIDDLEWARE = '@@REDUX_LOADING_MIDDLEWARE';
export const REDUX_LOADING_MIDDLEWARE_START_LOADING = `${REDUX_LOADING_MIDDLEWARE}/START_LOADING`;
export const REDUX_LOADING_MIDDLEWARE_FINISH_LOADING = `${REDUX_LOADING_MIDDLEWARE}/FINISH_LOADING`;
