export const REDUX_PENDING_MIDDLEWARE = '@@REDUX_PENDING_MIDDLEWARE';
export const REDUX_PENDING_MIDDLEWARE_START_REQUEST =
  '@@REDUX_PENDING_MIDDLEWARE/START_REQUEST';
export const REDUX_PENDING_MIDDLEWARE_FINISH_REQUEST =
  '@@REDUX_PENDING_MIDDLEWARE/FINISH_REQUEST';
